# Some of this logic was stolen from https://www.freecodecamp.org/news/a-lightweight-tool-agnostic-ci-cd-flow-with-github-actions/

name: terraform

on:
  push:
#   branches:
#     - master
  pull_request:

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29
      #   cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: run make
      # env:
      #   TOKEN: ${{ secrets.TOKEN }}
        run: |
          make all
